### ISSUE TITLE
set_ext_vcc fails

### ISSUE THREAD

**Issue by brvdboss** [charkster/mcp4728#1]
Hello,

lines 282-283 in MCP4728.py are missing the self. reference
```
		if (vcc < 0.0 or vcc > __MAX_EXT_VCC):
			print("External Vcc must be between 0 and {:.2f}V".format(__MAX_EXT_VCC))
			return -1
```

should be
```
		if (vcc < 0.0 or vcc > self.__MAX_EXT_VCC):
			print("External Vcc must be between 0 and {:.2f}V".format(self.__MAX_EXT_VCC))
			return -1
```

**Comment by charkster** [comment]
@brvdboss Thanks! You are absolutely right. Do you want to be added as a contributor and make the change, or should I just make the change?

**Comment by brvdboss** [comment]
I suggest you just make the change.  Since it's such a small edit I was actually too lazy to go through the effort making a pull request to be honest ;)

I really like the simplicity and the fact you don't drag in any unneeded dependencies with this little library

**Comment by charkster** [comment]
@brvdboss I just made the checkin and referenced this issue number. I'm glad that you were able to use this... I specifically wrote it to have as few dependencies as possible (and to be as flat as possible). I could have made the class much smaller if I had just implemented the write functions and had the user specify all the parameters... it would be very explicit, but I was using the class to do many output voltage changes, and it was cleaner to just specify the new voltage and request the channel write.
If Microchip had used a register approach that supported read-modify-write instead of commands, that would have made the class much, much simpler too.
